---
assets:
  central-key: "g4s8/.rultor#assets/artipie/_artipie.central-cd"
  env.sh: "g4s8/.rultor#assets/artipie/env.sh"
docker:
  image: "g4s8/rultor:alpine3.11"
  as_root: true
install:
  - "apk --update --no-cache --no-progress add openssh docker docker-compose"
deploy:
  sensitive:
    - central-key
  script: |-
    eval $(ssh-agent)
    chmod 400 ../central-key
    ssh-add ../central-key
    echo "central.artipie.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBF1Gp8oOdXbutBD14uO0dQAHh82zTDdoIZ5awrG1M2gaC8BPZGVXbEFJj+LNu8lioKxnINn4eHRU3MvCHHCpx9E=" >> /etc/ssh/ssh_known_hosts
    scp nginx.con artipie@central.artipie.com:/home/artipie/central/nginx.conf
    scp artipie.yml artipie@central.artipie.com:/home/artipie/central/artipie.yml
    docker context create central.artipie.com --docker "host=ssh://artipie@central.artipie.com"
    docker context use central.artipie.com
    set +x
    source ../env.sh
    set -x
    docker-compose pull artipie
    docker-compose down
    docker-compose up -d
architect:
  - "g4s8"
