version: "3.3"
services:
  artipie:
    image: artipie/artipie:0.6.1
    container_name: artipie
    restart: unless-stopped
    environment:
      - ARTIPIE_USER_NAME
      - ARTIPIE_USER_PASS
      - ARTIPIE_SESSION_KEY
    volumes:
      - /var/artipie:/var/artipie
      - ./artipie.yml:/etc/artipie.yml
    networks:
      - artipie-net
  central-auth:
    image: g4s8/artipie-auth:latest
    container_name: central-auth
    environment:
      - OAUTH_CLIENT
      - OAUTH_SECRET
      - SESSION_KEY
    volumes:
      - /var/artipie/keys:/var/artipie/keys
    networks:
      - artipie-net
  nginx:
    image: nginx:1.17.10-alpine
    container_name: nginx
    depends_on:
      - artipie
      - central-auth
    restart: unless-stopped
    networks:
      - artipie-net
    volumes:
      - ${HOME}/central/www:/var/www
      - ${HOME}/central/nginx.conf:/etc/nginx/nginx.conf
      - ${HOME}/central/data/certbot/conf:/etc/letsencrypt
      - ${HOME}/central/data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ${HOME}/central/data/certbot/conf:/etc/letsencrypt
      - ${HOME}/central/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  artipie-net:
    driver: bridge
