version: "3.3"
services:
  artipie:
    image: artipie:latest
    container_name: artipie
    restart: unless-stopped
    volumes:
      - /var/artipie:/var/artipie
    networks:
      - artipie-net
  nginx:
    image: nginx:1.17.10-alpine
    container_name: nginx
    depends_on:
      - artipie
    restart: unless-stopped
    networks:
      - artipie-net
    volumes:
      - ${PWD}/central:/var/www/central
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
networks:
  artipie-net:
    driver: bridge
