name: "Deploy Artipie"
on: [push]
jobs:
  deploy:
    runs-on: [self-hosted]
    environment: Prod
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Deploy to Server
        env:
          http_proxy: "http://localhost:3128"
        run: |
          echo "$GITHUB_WORKSPACE"
