name: "Deploy Artipie"
on: [push]
jobs:
  deploy:
    runs-on: [self-hosted]
    environment: Prod
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Deploy to Server
        run: |
          apt -yq install rsync openssh-client
          rsync -r -o StrictHostKeyChecking=no -v /home/runner/myw/_work/central/central/* ssh://${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }} -v
          docker context create remote ‐‐docker "host=ssh://${{ secrets.REMOTE_HOST }}"
          docker context use remote
          docker-compose build
          docker-compose pull artipie
          docker-compose down
          docker-compose up -d
