name: "Deploy Artipie"
on: [push]
jobs:
  deploy:
    runs-on: [self-hosted]
    environment: Prod
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Deploy to Server
        env:
          http_proxy: "http://localhost:3128"
          REMOTE_TARGET: ${{secrets.REMOTE_TARGET}}
        run: |
          env>/tmp/log.log
          rsync -r -v $GITHUB_WORKSPACE/* "$REMOTE_TARGET"
          cd "$REMOTE_TARGET"
          ls -lah
          ./restart.sh
 
