name: "Deploy Artipie"
on: [push]
jobs:
  deploy:
    runs-on: [self-hosted]
    environment: Prod
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Deploy to Server
        run: |
          rsync -r /home/runner/myw/_work/central/central/* ${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }} -v
          echo "----- rsync passed successfully -----"
          docker context rm remote -f
          echo "----- remove context 'remote' -----"
          docker context create remote --docker "host=ssh://${{ secrets.REMOTE_HOST }}"
          echo "----- context was created -----"
          docker context use remote
          echo "----- used remote context -----"
          docker-compose build
          echo "----- built with docker-compose -----"
          docker-compose pull artipie
          echo "----- pulled artipie -----"
          docker-compose down
          echo "----- down successfully -----"
          docker-compose up -d
          echo "----- up in detached mode -----"
