name: "Deploy Artipie"
on: [push]
jobs:
  deploy:
    runs-on: [self-hosted]
    environment: Prod
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Deploy to Server
        env:
          http_proxy: "http://localhost:3128"
        run: |
          rsync -r /home/runner/myw/_work/central/central/* ${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }} -v
          echo "----- rsync passed successfully -----"
          ssh -c "./restart.sh"
          echo "----- successfully finished script -----"
