name: "Deploy Artipie"
on: [push]
jobs:
  deploy:
    runs-on: [self-hosted]
    environment: Prod
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Deploy to Server
        run: |
          rsync -r /home/runner/myw/_work/central/central/* ${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }} -v
          echo "rsync was established"
          docker context create remote ‐‐docker "host=ssh://${{ secrets.REMOTE_HOST }}"
          echo "context was created"
          docker context use remote
          echo "used remote context"
          docker-compose build
          docker-compose pull artipie
          docker-compose down
          docker-compose up -d
