name: "Deploy Artipie"
on: [push]
jobs:
  deploy:
    runs-on: [self-hosted]
    environment: Prod
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Deploy to Server
        env:
          http_proxy: "http://localhost:3128"
        run: |
          rsync -r /home/runner/myw/_work/central/central/* ${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }} -v
          echo "----- rsync passed successfully -----"
          docker context rm remote -f
          echo "----- remove context 'remote' -----"
          docker context create remote --docker "host=ssh://${{ secrets.REMOTE_HOST }}"
          echo "----- context was created -----"
          docker-compose --context remote --verbose build
          echo "----- built with docker-compose -----"
          docker-compose --context remote --verbose pull artipie
          echo "----- pulled artipie -----"
          env COMPOSE_PARAMIKO_SSH=1 docker-compose --context remote --verbose down
          echo "----- down successfully -----"
          docker-compose --context remote --verbose up -d
          echo "----- up in detached mode -----"
